version: '3'

services:
  sftp:
    image: atmoz/sftp
    container_name: sftp-server
    volumes:
      - ./sftp-server/upload:/home/foo/upload
    ports:
      - "2222:22"
    command: foo:pass:::upload
